### ISSUE TITLE
Support OpenAPI v3.0.0

### ISSUE THREAD

**Issue by Falinor** [Redocly/create-openapi-repo#15]
Could be nice, isn't it?

**Comment by RomanGotsiy** [comment]
This should be migrated to latest yeoman before because there are lots of breaking changes.

hopefully I will find some time this month to do this!

**Comment by LEAFERx** [comment]
Swagger Editor 3.x doesn't support backend, which means can't open backend swagger.yaml or write back. What about switch to https://github.com/Mermade/openapi-gui?
I may find some time to help upgrade this project and swagger-repo. This project is awesome and so unfortunately not supporting openapi 3.0

**Comment by lx1036** [comment]
Yes, this repo is not supporting openapi 3.0 now. Is there any plan about this?

**Comment by RomanGotsiy** [comment]
It is not yet supporting openapi 3.0 and there is a plan to support this.
I don't have any estimates yet though.

Will keep you updated in this thread.

**Comment by davidtauriello** [comment]
Hi @RomanHotsiy - Does create-openapi-repo support openapi 3.0 - ? Latest reply says it's in the works, but I've been having an issue in win10 x64 environment after `npm start`:

`Watching changes...
Error while bundling the API definition: The "path" argument must be of type string. Received type undefined`

HTML populates to browser, but it throws error:

Error: Document must be valid OpenAPI 3.0.0 definition
    at e.validate (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:108:41391)
    at new e (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:108:41188)
    at new <anonymous> (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:108:44733)
    at new e (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:114:25238)
    at t.makeStore (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:108:68539)
    at t.render (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:108:69467)
    at Ai (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:83:62905)
    at ji (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:83:62700)
    at Ni (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:83:66534)
    at Va (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:83:90551)

ReDoc Version: 2.0.0-rc.8-1 
Commit: 4d8cba1
