### ISSUE TITLE
Repository generation fails - Error: EACCES permission denied, open '/root/.config/configstore/insight-yo.json'

### ISSUE THREAD

**Issue by stevegoossens** [Redocly/create-openapi-repo#23]
Following the instructions, I ran the commands:

```
[root@laptop1 swagger-spec]# npm install -g yo
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js
/usr/local/bin/yo-complete -> /usr/local/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall


> yo@2.0.2 postinstall /usr/local/lib/node_modules/yo
10005 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/currently-unhandled
10006 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/decamelize
10007 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/decode-uri-component
10008 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/deep-extend
10009 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/deep-is
10010 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/delayed-stream
10011 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/combined-stream
10012 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/depd
10013 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/deref
10014 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/destroy
10015 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/detect-conflict
10016 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/detect-newline/node_modules/minimist
10017 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/diff
10018 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/dir-glob/node_modules/pify
10019 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/dir-glob/node_modules/path-type
10020 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/dir-glob
10021 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/dom-serializer/node_modules/domelementtype
10022 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/domelementtype
10023 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/domhandler
10024 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/domutils
10025 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/drange
10026 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/duplexer3
10027 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/ebnf-parser
10028 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/editions
10029 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/ee-first
10030 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/ejs
10031 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/encodeurl
10032 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/entities
10033 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/dom-serializer
10034 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/escape-html
10035 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/escape-string-regexp
10036 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/escodegen/node_modules/esprima
10037 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/esprima
10038 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/estraverse
10039 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/esutils
10040 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/etag
10041 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/exit-hook
10042 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/express/node_modules/iconv-lite
10043 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/express/node_modules/qs
10044 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/express/node_modules/raw-body/node_modules/depd
10045 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/express/node_modules/raw-body/node_modules/setprototypeof
10046 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/express/node_modules/statuses
10047 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/extend
10048 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/faker
10049 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/fast-levenshtein
10050 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/finalhandler/node_modules/statuses
10051 silly finalize /usr/local/lib/node_modules/generator-openapi-repo/node_modules/for-in
...skipping...
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
+ yo@2.0.2
added 538 packages in 95.907s
```

I used the `--ignore-scripts` option as nomnom is deprecated and causes the `jsonpath` module install to fail.
```
[root@laptop1 swagger-spec]# npm install --ignore-scripts -g generator-openapi-repo
npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
+ generator-openapi-repo@1.0.1
added 647 packages in 105.491s
```

so now I should be able to generate the content, right?
```
[root@laptop1 ~]# yo openapi-repo
/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Configstore.get (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Configstore.get (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:81:13)
    at Insight.get (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:48:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:197:47)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```
wrong...

I don't know what permissions problem is supposed to be as I'm running the command as root and the file has open permissions for root and I can access the file
```
[root@laptop1 ~]# ll /root/.config/configstore/insight-yo.json
-rw------- 1 root root 30 May 29 17:26 /root/.config/configstore/insight-yo.json
[root@laptop1 ~]# ll /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js
-rw-r--r-- 1 root root 2666 Dec  9  2015 /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js
[root@laptop1 ~]# whoami
root
[root@laptop1 ~]# cat /root/.config/configstore/insight-yo.json
{
	"clientId": 1330252673930
}
```

**Comment by RomanHotsiy** [comment]
Closing as stale
